### ISSUE TITLE
마이너 이슈 반영

### ISSUE THREAD

**Issue by jaegeunlee-29cm** [mpruser/tooln-share#3]
### 변경사항
@mpruser  재관님, 추가로 발견한 부분인데요.
2가지 이슈 모두 PC 구간 혹은 PC <-> 모바일 전환 시 발생한 이슈였습니다.
확인해보시고, 추가로 이슈있으시면 말씀주세요!

- scale 속성 적용구간 너비가 잘못 계산되는 이슈 반영 https://github.com/mpruser/tooln-share/commit/60faaa25ff96895575dbd08164e650a8c3826364
  - `transform: scale()` 값이 변경되는 마우스 휠 구간의 너비가 너무 좁게 잡히고 있어서,
해당 섹션 전체 너비에 적용되게끔 수정했습니다.
- 리사이징 시, 간헐적으로 이미지 scale 적용되지 않는 이슈 반영 https://github.com/mpruser/tooln-share/commit/6307789dc7814838e8ca332b60e6f215eabc6dfa
  - PC <-> 모바일 전환 시, scale 속성값이 제대로 반영되지 않는 이슈가 있어 테스트 해봤는데,
기존에 `gsap.from()` 방식에서, `gsap.to()` (+ css에서 scale: 1.2를 default로) 방식이
좀더 안정적으로 구동되는 것 같습니다.

**Comment by mpruser** [comment]
더 좋아 진 것 같아요:) 방금 디자이너한테 피드백왔는데 모션도 그렇고 전체적으로 완벽하다고 너무 좋다고 하시네요:)
아직 끝나지는 않았지만.. 고생많으셨어요!!
